/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/assess": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Assess a document quote, risks and route without spend */
        post: operations["assess_job_jobs_assess_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stage a source document server-side; returns the input_path to submit */
        post: operations["upload_source_document_jobs_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Job */
        post: operations["submit_job_jobs_submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Jobs
         * @description The job queue: every ledger in ``db_dir``, newest first.
         *
         *     Reads the durable store (one ``{job_id}.sqlite`` per job) so a restarted
         *     console still lists finished jobs, and overlays live jobs with the
         *     manager's in-memory progress (fresher than the ``job_meta`` row a run
         *     only finalizes at the end).
         *
         *     ``GET /jobs`` is also the console's Mission Control URL, so a browser
         *     navigation (``Accept: text/html``) is answered with the SPA shell and
         *     the client router resolves the screen; API clients get the JSON queue.
         */
        get: operations["list_jobs_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Job
         * @description Cancel an in-flight job (idempotent: terminal jobs return as-is).
         */
        post: operations["cancel_job_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resume Job
         * @description Re-run a failed/cancelled job from its ledger checkpoints (PRD §4.2.4).
         *
         *     The pipeline resumes from the blocks still pending in the ledger, so no
         *     finished segment is re-translated. Resume reuses the *original* request
         *     (kept on the in-memory record), which keeps the run-identity guard happy
         *     — a reconstructed request would silently drop knobs and could be refused
         *     as a different profile/engine. That makes this a same-session recovery
         *     (the network-drop case); a job whose record is gone after a restart must
         *     be resubmitted instead.
         */
        post: operations["resume_job_jobs__job_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove a finished job's ledger and deliverables from the console
         * @description Delete one job's history: the db_dir ledger plus its deliverable dir.
         *
         *     A running job must reach a terminal status first — deletion is history
         *     management, not a stop button. A non-terminal queue-mode record is
         *     likewise refused: the durable queue owns its rows (``prune_terminal``
         *     is their lifecycle) and removing the ledger underneath a worker would
         *     desynchronize its view.
         */
        delete: operations["delete_job_jobs__job_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Status */
        get: operations["get_status_jobs__job_id__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Progress
         * @description SSE: ``event: progress`` snapshots until one ``event: <status>`` terminal frame.
         *
         *     Both deployment modes emit that one contract (see ``_progress_frame`` /
         *     ``_terminal_frame``); the payload never depends on how the server was
         *     started. Every frame carries an ``id:`` cursor, so a client reconnecting
         *     with ``Last-Event-ID`` (header or ``?last_event_id=``) receives the
         *     frames it missed before the live stream resumes (PRD §9.2).
         */
        get: operations["stream_progress_jobs__job_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Report */
        get: operations["get_report_jobs__job_id__report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/visual-report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Visual Report */
        get: operations["get_visual_report_jobs__job_id__visual_report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download File */
        get: operations["download_file_jobs__job_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/deliverables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Deliverables
         * @description List the deliverables a finished job actually left on disk.
         *
         *     A run may emit a rigid companion, a complementary dual/mono render, an
         *     EPUB and the JSON sidecars depending on its flags; the UI must render
         *     only what exists rather than offer four fixed buttons. Keys match
         *     :data:`DELIVERABLE_LABELS`.
         */
        get: operations["list_deliverables_jobs__job_id__deliverables_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/download/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Deliverable
         * @description Serve one deliverable by key (see :data:`DELIVERABLE_LABELS`).
         */
        get: operations["download_deliverable_jobs__job_id__download__key__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/segments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Segments
         * @description A page of a job's finalized blocks for the workbench grid.
         *
         *     ``status=issues`` returns everything the fault ribbon counts plus the
         *     PE-queue members; a concrete ``BlockStatus`` value filters by lifecycle
         *     status. Blocks are projected with their source/target, QE score, flags
         *     and grouped issue kinds.
         */
        get: operations["list_segments_jobs__job_id__segments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/issues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Issues
         * @description Fault-ribbon counts by issue kind, plus terminology drift detail.
         */
        get: operations["list_issues_jobs__job_id__issues_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/segments/{block_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Edit Segment
         * @description Apply one human revision (ledger + shared TM), the L3 feedback path.
         */
        post: operations["edit_segment_jobs__job_id__segments__block_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/segments/{block_id}/terms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Segment Terms
         * @description Terminology findings for one block, with the cascade size each implies.
         *
         *     Each finding carries the offending ``surface``, the ``expected``
         *     rendering, and how many *other* blocks in the job carry the same
         *     error — ``cascade_all`` for the whole book, ``cascade_subsequent`` for
         *     blocks at or after this one. This is what the "fix all N" checkbox
         *     counts.
         */
        get: operations["segment_terms_jobs__job_id__segments__block_id__terms_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/term-propagation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Propagate Term
         * @description Replace one offending term surface across the job (PRD §5.2.2).
         *
         *     Rewrites the selected block and, per ``scope``, every matching block;
         *     each rewritten block is promoted to a human revision and its pair fed
         *     back to the shared TM, exactly like a manual edit.
         */
        post: operations["propagate_term_jobs__job_id__term_propagation_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/pages/{page}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Preview Page
         * @description Re-compose one source page with the current ledger text, as PNG.
         *
         *     Reuses the delivery compositor (source page as canvas) for a single page,
         *     so a human edit can be previewed without re-rendering the book. 503 when
         *     the page has nothing to compose or the rasterizer is unavailable.
         */
        get: operations["preview_page_jobs__job_id__pages__page__preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/pages/{page}/source": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Source Page
         * @description Rasterize the *source* PDF's page ``page`` as PNG.
         *
         *     The "before" half of the L3 pixel-witness view; pairs with
         *     ``/pages/{page}/preview`` (the composed "after"). 503 when the source is
         *     missing or the rasterizer is unavailable.
         */
        get: operations["source_page_jobs__job_id__pages__page__source_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/model-profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Model Profiles
         * @description List all currently registered model capability profiles.
         */
        get: operations["list_model_profiles_api_v1_model_profiles_get"];
        put?: never;
        /**
         * Register Model Profile
         * @description Register a custom model capability profile (built-in profiles cannot be overridden).
         */
        post: operations["register_model_profile_api_v1_model_profiles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/doctor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * System Doctor
         * @description Engine Doctor self-check (the ``ubt doctor`` checklist as JSON).
         *
         *     Reuses the CLI's ``collect_checks`` so the console and the command line
         *     report the same verdicts. ``probe=true`` additionally contacts the
         *     provider endpoint (a live network call), so it is off by default.
         */
        get: operations["system_doctor_system_doctor_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * System Info
         * @description The console's security-boundary panel (real host + allowed roots).
         *
         *     Reports the host this request reached (loopback vs exposed), whether the
         *     API-key gate is on, and the filesystem roots ``resolve_secure_path``
         *     actually enforces — so the panel shows the live policy, not a hardcoded
         *     sample.
         */
        get: operations["system_info_system_info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/glossary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Glossary */
        get: operations["get_glossary_assets_glossary_get"];
        put?: never;
        /** Upsert Glossary Term */
        post: operations["upsert_glossary_term_assets_glossary_post"];
        /** Delete Glossary Term */
        delete: operations["delete_glossary_term_assets_glossary_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/glossary/conflicts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Glossary Conflicts
         * @description Sources configured with more than one target rendering (PRD §4.4.2).
         */
        get: operations["get_glossary_conflicts_assets_glossary_conflicts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/tm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Translation Memory */
        get: operations["get_translation_memory_assets_tm_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/tm/evict": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Evict Translation Memory */
        post: operations["evict_translation_memory_assets_tm_evict_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/tm/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Translation Memory
         * @description Import TMX/JSON pairs into the shared TM (machine provenance by default).
         *
         *     An import is unverified, so the default ``machine`` provenance cannot
         *     downgrade an existing ``human_pe`` row (the store's writeback enforces
         *     that). Parsing is strict: a malformed payload is a 422, not a silent
         *     empty import.
         */
        post: operations["import_translation_memory_assets_tm_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AssessCost
         * @description The cost quote, split by component so the UI can show the drivers.
         */
        AssessCost: {
            /** Draft Model */
            draft_model: string;
            /** Repair Model */
            repair_model: string;
            /** Prefix Tokens Per Call */
            prefix_tokens_per_call?: number | null;
            /** Billable Blocks */
            billable_blocks: number;
            /** Billable Blocks Is Exact */
            billable_blocks_is_exact: boolean;
            /** Prompt Tokens */
            prompt_tokens: number;
            /** Completion Tokens */
            completion_tokens: number;
            /** Draft Cost Usd Cached */
            draft_cost_usd_cached?: number | null;
            /** Draft Cost Usd Uncached */
            draft_cost_usd_uncached?: number | null;
            /** Repair Blocks */
            repair_blocks: number;
            /** Repair Cost Usd */
            repair_cost_usd?: number | null;
            /** Qe Calls */
            qe_calls: number;
            /** Qe Cost Usd */
            qe_cost_usd?: number | null;
            /** Vlm Page Calls */
            vlm_page_calls: number;
            /** Ocr Page Calls */
            ocr_page_calls: number;
            /** Vision Cost Usd */
            vision_cost_usd?: number | null;
            /** Rollup Calls */
            rollup_calls: number;
            /** Total Cost Usd */
            total_cost_usd?: number | null;
        };
        /**
         * AssessDocumentFacts
         * @description Structural facts about the source document.
         */
        AssessDocumentFacts: {
            /** File Name */
            file_name: string;
            /** File Size Bytes */
            file_size_bytes: number;
            /** Format Ext */
            format_ext: string;
            /** Pages */
            pages: number;
            /** Chapters */
            chapters: number;
            /** Source Chars */
            source_chars: number;
            /** Estimated Tokens */
            estimated_tokens: number;
            /** Category */
            category: string;
            /** Detected Domain */
            detected_domain: string;
            /** Domain Confidence */
            domain_confidence: number;
            /** Math Density */
            math_density: string;
            /** Is Scanned */
            is_scanned: boolean;
            /** Primary Engine */
            primary_engine?: string | null;
            /** Has Vector Diagrams */
            has_vector_diagrams?: boolean | null;
            /** Has Multicolumn */
            has_multicolumn?: boolean | null;
            /** Has Formulas */
            has_formulas?: boolean | null;
            /** Text Layer Coverage */
            text_layer_coverage?: number | null;
            /** Scan Page Share */
            scan_page_share?: number | null;
        };
        /**
         * AssessRoute
         * @description The engine's recommended routing for this document.
         */
        AssessRoute: {
            /** Mode */
            mode: string;
            /** Reason */
            reason: string;
            /** Recommended Preset */
            recommended_preset: string;
            /** Recommended Render Engine */
            recommended_render_engine: string;
            /** Recommended Dual Mode */
            recommended_dual_mode: string;
            /** Recommended Profile */
            recommended_profile: string;
            /** Confidence */
            confidence: number;
            /** Confidence Basis */
            confidence_basis: string;
        };
        /**
         * AssessRuntime
         * @description A heuristic wall-clock estimate (no per-stage history is persisted).
         */
        AssessRuntime: {
            /** Heuristic */
            heuristic: boolean;
            /** Est Seconds Low */
            est_seconds_low: number;
            /** Est Seconds High */
            est_seconds_high: number;
            /** Basis */
            basis: string;
        };
        /**
         * AssessWarning
         * @description One degraded probe: a stable machine code plus Chinese human copy.
         */
        AssessWarning: {
            /** Code */
            code: string;
            /** Level */
            level: string;
            /** Detail Zh */
            detail_zh: string;
        };
        /** Body_upload_source_document_jobs_upload_post */
        Body_upload_source_document_jobs_upload_post: {
            /** File */
            file: string;
        };
        /**
         * ExtractionStrategy
         * @description Output extraction strategy.
         * @enum {string}
         */
        ExtractionStrategy: "xml_tag" | "raw" | "cp" | "auto";
        /**
         * GlossaryTermRequest
         * @description One glossary term to add to (or remove from) the configured glossary file.
         */
        GlossaryTermRequest: {
            /**
             * Source
             * @description Source term
             */
            source: string;
            /**
             * Target
             * @description Target translation (required when adding)
             * @default
             */
            target: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * JobAssessRequest
         * @description Payload to assess a cold document without translating.
         */
        JobAssessRequest: {
            /**
             * Input Path
             * @description Path to source document file
             */
            input_path: string;
            /**
             * Deep
             * @description Run deep real adapter ingest for exact counts
             * @default false
             */
            deep: boolean;
            /**
             * Target Lang
             * @description Target ISO language code
             * @default zh
             */
            target_lang: string;
            /**
             * Source Lang
             * @description Source ISO language code
             * @default en
             */
            source_lang: string;
            /** @description Quality preset (publication, standard, preview) */
            preset?: components["schemas"]["Preset"] | null;
        };
        /**
         * JobAssessResponse
         * @description The full pre-flight assessment report.
         */
        JobAssessResponse: {
            /** Schema Version */
            schema_version: number;
            /** Status */
            status: string;
            /** Path */
            path: string;
            /** Deep */
            deep: boolean;
            document: components["schemas"]["AssessDocumentFacts"];
            route: components["schemas"]["AssessRoute"];
            cost: components["schemas"]["AssessCost"];
            runtime: components["schemas"]["AssessRuntime"];
            /** Quality Signals */
            quality_signals: string[];
            /** Warnings */
            warnings: components["schemas"]["AssessWarning"][];
            /** Next Step Command */
            next_step_command: string;
            /** Meta */
            meta: {
                [key: string]: unknown;
            };
        };
        /**
         * JobDeleteResponse
         * @description Result of removing a finished job's history from the console.
         */
        JobDeleteResponse: {
            /** Job Id */
            job_id: string;
            /**
             * Removed Ledger
             * @description The db_dir ledger file(s) were deleted
             */
            removed_ledger: boolean;
            /**
             * Removed Outputs
             * @description The per-job deliverable directory was deleted
             */
            removed_outputs: boolean;
        };
        /**
         * JobListResponse
         * @description The job queue, newest first.
         */
        JobListResponse: {
            /** Jobs */
            jobs: components["schemas"]["JobSummary"][];
        };
        /**
         * JobStatusResponse
         * @description Real-time job status and metric counters.
         *
         *     The telemetry fields are the shared :class:`ProgressSnapshot` -- one
         *     definition for the queue row, the in-memory record and this response.
         */
        JobStatusResponse: {
            /**
             * Total Blocks
             * @default 0
             */
            total_blocks: number;
            /**
             * Completed Blocks
             * @default 0
             */
            completed_blocks: number;
            /**
             * Repaired Blocks
             * @default 0
             */
            repaired_blocks: number;
            /**
             * Failed Blocks
             * @default 0
             */
            failed_blocks: number;
            /**
             * Needs Human Blocks
             * @default 0
             */
            needs_human_blocks: number;
            /**
             * Blocked Human Blocks
             * @default 0
             */
            blocked_human_blocks: number;
            /**
             * Processed Blocks
             * @default 0
             */
            processed_blocks: number;
            /**
             * Progress Percent
             * @default 0
             */
            progress_percent: number;
            /**
             * Current Avg Qe
             * @default 0
             */
            current_avg_qe: number;
            /**
             * Bottom 15 Avg Qe
             * @default 0
             */
            bottom_15_avg_qe: number;
            /** Estimated Cost Usd */
            estimated_cost_usd?: number | null;
            /** Output File */
            output_file?: string | null;
            /** Report File */
            report_file?: string | null;
            /** Visual Report File */
            visual_report_file?: string | null;
            /** Job Id */
            job_id: string;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error */
            error?: string | null;
            /** Queue Position */
            queue_position?: number | null;
            /**
             * Rehearsal
             * @default false
             */
            rehearsal: boolean;
        };
        /**
         * JobSubmitRequest
         * @description Payload to initiate an asynchronous translation job.
         */
        JobSubmitRequest: {
            /**
             * Input Path
             * @description Path to source document file
             */
            input_path: string;
            /**
             * Output Path
             * @description Optional target path for bilingual file
             */
            output_path?: string | null;
            /**
             * Target Lang
             * @description Target ISO language code
             * @default zh
             */
            target_lang: string;
            /**
             * Source Lang
             * @description Source ISO language code
             * @default en
             */
            source_lang: string;
            /**
             * Profile
             * @description Domain profile (general, textbook, paper)
             * @default general
             */
            profile: string;
            /**
             * Draft Model
             * @description Override draft model tier
             */
            draft_model?: string | null;
            /**
             * Repair Model
             * @description Override repair model tier
             */
            repair_model?: string | null;
            /** @description Quality preset (publication, standard, preview) */
            preset?: components["schemas"]["Preset"] | null;
            /**
             * Render Engine
             * @description PDF render engine (rigid, reflow, publication, auto)
             */
            render_engine?: ("rigid" | "reflow" | "auto" | "publication" | "composite") | null;
            /**
             * Pdf Engine
             * @description PDF extraction/parser engine (docling, pdfium, auto)
             */
            pdf_engine?: string | null;
            /**
             * Dual Mode
             * @description Bilingual mode (inline, alternating, facing, monolingual, auto)
             */
            dual_mode?: ("inline" | "alternating" | "monolingual" | "facing" | "auto") | null;
            /**
             * Pages
             * @description Page range filter (e.g. 1-10)
             */
            pages?: string | null;
            /**
             * Glossary
             * @description Path to an external glossary file to enforce (CLI/MCP parity)
             */
            glossary?: string | null;
            /**
             * Exec Mode
             * @description Execution mode (auto, short, long)
             */
            exec_mode?: ("auto" | "short" | "long") | null;
            /**
             * Formula Mode
             * @description Formula handling (strict, readable)
             */
            formula_mode?: ("strict" | "readable") | null;
            /**
             * Budget Usd
             * @description Hard USD cap for this job across every resume; the run fails once priced cost exceeds it
             */
            budget_usd?: number | null;
            /**
             * Max Concurrency
             * @description Concurrent LLM requests for this job
             */
            max_concurrency?: number | null;
            /**
             * Batch Limit
             * @description Blocks per draft batch
             */
            batch_limit?: number | null;
            /**
             * Macro Chunk Size
             * @description Consecutive micro-blocks packed into one draft request (1 = single block)
             */
            macro_chunk_size?: number | null;
            /**
             * Short Max Pages
             * @description Page ceiling for the short execution chain
             */
            short_max_pages?: number | null;
            /**
             * Enable Rolling Summary
             * @description Carry a rolling chapter summary across draft batches
             */
            enable_rolling_summary?: boolean | null;
            /**
             * Chapter Streaming Enabled
             * @description Translate chapter-by-chapter as discovery lands
             */
            chapter_streaming_enabled?: boolean | null;
            /**
             * Offline Batch Enabled
             * @description Route drafting through the provider's offline batch API
             */
            offline_batch_enabled?: boolean | null;
            /**
             * Qe Engine
             * @description QE runner (heuristic, comet, cometkiwi, neural, subprocess, tiered)
             */
            qe_engine?: ("heuristic" | "comet" | "cometkiwi" | "neural" | "subprocess" | "tiered") | null;
            /**
             * Visual Judge Enabled
             * @description Enable the VLM visual judge over rendered pages
             */
            visual_judge_enabled?: boolean | null;
            /**
             * Visual Judge Model
             * @description Model the visual judge runs on
             */
            visual_judge_model?: string | null;
            /**
             * Prompt Strategy
             * @description Prompt depth (auto, minimal, hybrid, rich)
             */
            prompt_strategy?: ("auto" | "minimal" | "hybrid" | "rich") | null;
            /**
             * Translate Chrome
             * @description Translate running heads, footers and page chrome
             */
            translate_chrome?: boolean | null;
            /**
             * Facing Spread
             * @description Lay the bilingual output out as facing pages
             */
            facing_spread?: boolean | null;
            /**
             * Emit Both
             * @description Emit both the reflow and the rigid deliverable
             */
            emit_both?: boolean | null;
            /**
             * Emit Companion Rigid
             * @description Emit a zero-cost '*_rigid.pdf' source-fidelity companion alongside the reflow output
             */
            emit_companion_rigid?: boolean | null;
            /**
             * Cover Mode
             * @description Cover handling (auto, always, never)
             */
            cover_mode?: ("auto" | "always" | "never") | null;
            /**
             * Formula Enrichment
             * @description Formula enrichment (auto, on, off)
             */
            formula_enrichment?: ("auto" | "on" | "off") | null;
            /**
             * Formula Render
             * @description Formula rendering (native, image, witness)
             */
            formula_render?: ("native" | "image" | "witness") | null;
            /**
             * Math Backend
             * @description Math typesetting backend (typst, mathjax, image)
             */
            math_backend?: ("typst" | "mathjax" | "image") | null;
            /**
             * Ocr Mode
             * @description OCR engine (auto, sidecar, cloud, vlm, rapidocr, off)
             */
            ocr_mode?: ("auto" | "sidecar" | "cloud" | "vlm" | "rapidocr" | "off") | null;
            /**
             * Domain
             * @description Domain descriptor used for glossary and chrome hints
             */
            domain?: string | null;
            /**
             * Job Id
             * @description Optional stable job id (idempotency key)
             */
            job_id?: string | null;
            /**
             * Priority
             * @description Queue priority (higher = sooner)
             * @default 0
             */
            priority: number;
            /**
             * Dry Run
             * @description Zero-token rehearsal run (echo provider)
             * @default false
             */
            dry_run: boolean;
            /**
             * Fresh
             * @description Discard prior ledger state instead of resuming (unset follows UBT_FRESH)
             */
            fresh?: boolean | null;
            /**
             * Start Chapter
             * @description First chapter of the window (run-only key)
             */
            start_chapter?: number | null;
            /**
             * Max Chapters
             * @description Chapter-window length (run-only key)
             */
            max_chapters?: number | null;
        };
        /**
         * JobSubmitResponse
         * @description Response returned upon successful job enqueueing.
         */
        JobSubmitResponse: {
            /** Job Id */
            job_id: string;
            /** Status */
            status: string;
            /** Stream Url */
            stream_url: string;
            /** Status Url */
            status_url: string;
            /**
             * Rehearsal
             * @default false
             */
            rehearsal: boolean;
        };
        /**
         * JobSummary
         * @description One row of the operator console's job queue.
         */
        JobSummary: {
            /** Job Id */
            job_id: string;
            /** File Name */
            file_name: string;
            /** Source Path */
            source_path: string;
            /** Target Lang */
            target_lang: string;
            /** Status */
            status: string;
            /** Total Blocks */
            total_blocks: number;
            /** Completed Blocks */
            completed_blocks: number;
            /** Failed Blocks */
            failed_blocks: number;
            /** Needs Human Blocks */
            needs_human_blocks: number;
            /** Progress Percent */
            progress_percent: number;
            /** Estimated Cost Usd */
            estimated_cost_usd?: number | null;
            /** Created At */
            created_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
            /** Has Output */
            has_output: boolean;
        };
        /**
         * JobUploadResponse
         * @description Result of staging an uploaded source document on the server.
         */
        JobUploadResponse: {
            /**
             * File Path
             * @description Server-side path to pass as input_path
             */
            file_path: string;
            /**
             * File Name
             * @description Original client-side file name
             */
            file_name: string;
            /**
             * Size Bytes
             * @description Stored file size in bytes
             */
            size_bytes: number;
        };
        /**
         * ModelProfile
         * @description Declarative capability profile for a translation model.
         *
         *     Decouples model execution logic from brittle name matching, enabling
         *     enterprise self-hosted models to configure behavior declaratively.
         */
        ModelProfile: {
            /**
             * Model Pattern
             * @description Exact model name or substring pattern used to resolve this profile.
             */
            model_pattern: string;
            /**
             * @description Prompt assembly strategy (RICH, MINIMAL, HYBRID).
             * @default rich
             */
            prompt_strategy: components["schemas"]["PromptStrategy"];
            /**
             * @description Output parsing strategy (XML_TAG, RAW, CONVERSATIONAL_PREFIX, AUTO).
             * @default auto
             */
            extraction_strategy: components["schemas"]["ExtractionStrategy"];
            /**
             * Supports Reasoning Effort
             * @description Whether the provider/model accepts the reasoning_effort parameter.
             * @default false
             */
            supports_reasoning_effort: boolean;
            /**
             * Supports System Prompt
             * @description Whether the model supports system turns; if False, merged into user prompt.
             * @default true
             */
            supports_system_prompt: boolean;
            /**
             * Supports Temperature
             * @description Whether model supports explicit temperature control.
             * @default true
             */
            supports_temperature: boolean;
            /**
             * Supports Vision
             * @description Whether the model natively accepts image inputs (multimodal / VLM).
             * @default false
             */
            supports_vision: boolean;
            /**
             * Display Name
             * @description Human-readable model name for diagnostics and logging.
             * @default
             */
            display_name: string;
            /**
             * Deployment Backend
             * @description Backend identifier if specialized. The self-hosted families ('self_hosted', 'ollama', 'llama.cpp', 'llama-swap', 'vllm', 'lmstudio', ...) enable the local retry when a gateway drops the model; 'ollama' is kept as a legacy alias.
             * @default
             */
            deployment_backend: string;
        };
        /**
         * Preset
         * @description User-facing quality tiers.
         * @enum {string}
         */
        Preset: "publication" | "standard" | "preview" | "fast";
        /**
         * PromptStrategy
         * @description Prompt assembly strategy.
         * @enum {string}
         */
        PromptStrategy: "rich" | "minimal" | "hybrid";
        /**
         * SegmentEditRequest
         * @description A human post-edit of one block's target text (L3 workbench).
         */
        SegmentEditRequest: {
            /**
             * Target Text
             * @description Revised target text
             */
            target_text: string;
        };
        /**
         * SystemInfoResponse
         * @description The console's security-boundary panel: where this server is reachable and
         *     what it is allowed to touch.
         */
        SystemInfoResponse: {
            /** Version */
            version: string;
            /**
             * Host
             * @description Host this request reached (client-visible)
             */
            host: string;
            /**
             * Is Loopback
             * @description True when the request arrived on a loopback host
             */
            is_loopback: boolean;
            /**
             * Auth Enabled
             * @description True when an API key gate is configured
             */
            auth_enabled: boolean;
            /**
             * Allowed Bases
             * @description Filesystem roots the server will read/write
             */
            allowed_bases: string[];
            /** Db Dir */
            db_dir: string;
            /**
             * Job Mode
             * @description embedded (in-process) or queue (worker-drained)
             */
            job_mode: string;
        };
        /**
         * TMImportRequest
         * @description Import translation-memory pairs from a TMX or JSON payload (L4 assets).
         */
        TMImportRequest: {
            /**
             * Format
             * @description Payload format
             * @enum {string}
             */
            format: "tmx" | "json";
            /**
             * Content
             * @description Raw TMX XML or JSON text
             */
            content: string;
            /**
             * Src Lang
             * @description Fallback source language for rows without one
             */
            src_lang: string;
            /**
             * Tgt Lang
             * @description Fallback target language for rows without one
             */
            tgt_lang: string;
            /**
             * Provenance
             * @description machine = unverified import (cannot downgrade existing human rows)
             * @default machine
             * @enum {string}
             */
            provenance: "machine" | "human_pe";
        };
        /**
         * TMevictRequest
         * @description Translation-memory rows to evict, by id.
         */
        TMevictRequest: {
            /**
             * Ids
             * @description TM entry ids to delete
             */
            ids?: number[];
        };
        /**
         * TermPropagationRequest
         * @description Replace one offending term surface with its canonical rendering (L3).
         */
        TermPropagationRequest: {
            /**
             * Block Id
             * @description Block the action was invoked from
             */
            block_id: string;
            /**
             * Surface
             * @description Offending surface to replace
             */
            surface: string;
            /**
             * Expected
             * @description Canonical rendering to write
             */
            expected: string;
            /**
             * Scope
             * @description block = only this block, subsequent = this and later blocks, all = whole book
             * @default all
             * @enum {string}
             */
            scope: "block" | "subsequent" | "all";
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assess_job_jobs_assess_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobAssessRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobAssessResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_source_document_jobs_upload_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_source_document_jobs_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_job_jobs_submit_post: {
        parameters: {
            query?: never;
            header?: {
                "x-ubt-tenant"?: string | null;
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobSubmitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobSubmitResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_jobs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                "x-ubt-tenant"?: string | null;
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: {
                "x-ubt-tenant"?: string | null;
                "x-api-key"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_job_jobs__job_id__resume_post: {
        parameters: {
            query?: never;
            header?: {
                "x-ubt-tenant"?: string | null;
                "x-api-key"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_job_jobs__job_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-ubt-tenant"?: string | null;
                "x-api-key"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_status_jobs__job_id__status_get: {
        parameters: {
            query?: never;
            header?: {
                "x-ubt-tenant"?: string | null;
                "x-api-key"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_progress_jobs__job_id__stream_get: {
        parameters: {
            query?: never;
            header?: {
                "x-ubt-tenant"?: string | null;
                "x-api-key"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_jobs__job_id__report_get: {
        parameters: {
            query?: never;
            header?: {
                "x-ubt-tenant"?: string | null;
                "x-api-key"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_visual_report_jobs__job_id__visual_report_get: {
        parameters: {
            query?: never;
            header?: {
                "x-ubt-tenant"?: string | null;
                "x-api-key"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_file_jobs__job_id__download_get: {
        parameters: {
            query?: never;
            header?: {
                "x-ubt-tenant"?: string | null;
                "x-api-key"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_deliverables_jobs__job_id__deliverables_get: {
        parameters: {
            query?: never;
            header?: {
                "x-ubt-tenant"?: string | null;
                "x-api-key"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_deliverable_jobs__job_id__download__key__get: {
        parameters: {
            query?: never;
            header?: {
                "x-ubt-tenant"?: string | null;
                "x-api-key"?: string | null;
            };
            path: {
                job_id: string;
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_segments_jobs__job_id__segments_get: {
        parameters: {
            query?: {
                status?: string | null;
                block_type?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: {
                "x-ubt-tenant"?: string | null;
                "x-api-key"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_issues_jobs__job_id__issues_get: {
        parameters: {
            query?: never;
            header?: {
                "x-ubt-tenant"?: string | null;
                "x-api-key"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_segment_jobs__job_id__segments__block_id__post: {
        parameters: {
            query?: never;
            header?: {
                "x-ubt-tenant"?: string | null;
                "x-api-key"?: string | null;
            };
            path: {
                job_id: string;
                block_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SegmentEditRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    segment_terms_jobs__job_id__segments__block_id__terms_get: {
        parameters: {
            query?: never;
            header?: {
                "x-ubt-tenant"?: string | null;
                "x-api-key"?: string | null;
            };
            path: {
                job_id: string;
                block_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    propagate_term_jobs__job_id__term_propagation_post: {
        parameters: {
            query?: never;
            header?: {
                "x-ubt-tenant"?: string | null;
                "x-api-key"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TermPropagationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_page_jobs__job_id__pages__page__preview_get: {
        parameters: {
            query?: {
                dpi?: number;
                bilingual?: boolean;
            };
            header?: {
                "x-ubt-tenant"?: string | null;
                "x-api-key"?: string | null;
            };
            path: {
                job_id: string;
                page: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    source_page_jobs__job_id__pages__page__source_get: {
        parameters: {
            query?: {
                dpi?: number;
            };
            header?: {
                "x-ubt-tenant"?: string | null;
                "x-api-key"?: string | null;
            };
            path: {
                job_id: string;
                page: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_model_profiles_api_v1_model_profiles_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelProfile"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_model_profile_api_v1_model_profiles_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelProfile"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    system_doctor_system_doctor_get: {
        parameters: {
            query?: {
                probe?: boolean;
            };
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    system_info_system_info_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemInfoResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_glossary_assets_glossary_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upsert_glossary_term_assets_glossary_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GlossaryTermRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_glossary_term_assets_glossary_delete: {
        parameters: {
            query: {
                source: string;
            };
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_glossary_conflicts_assets_glossary_conflicts_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_translation_memory_assets_tm_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                src_lang?: string | null;
                tgt_lang?: string | null;
            };
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evict_translation_memory_assets_tm_evict_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TMevictRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_translation_memory_assets_tm_import_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TMImportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
