"""R2: label-free bibliography detection (references stay in English).

Industry standard (GB/T 7714 practice, "外文文献一般对原始文献不作翻译"):
author names, venues, publishers, years, pages, and DOIs are never
translated — doing so breaks retrievability and is never deliverable.
Segmentation often drops the "[n]" label, so detection must work on the
entry content alone (tiers A/B in skip_rules).
"""

import pytest

from ubt.core.cleaners.skip_rules import classify_skip

pytestmark = pytest.mark.fast

BIB = "bibliography entry (kept verbatim for retrievability)"

# Real entries from docs/synthetic-mono.pdf (labels stripped, as segmented).
# Reference entries from the synthetic corpus (docs/synthetic-*.pdf,
# generated by scripts/make_sample_corpus.py), labels stripped as segmented.
# The shapes mirror the retired Elsevier samples: single-author book, journal,
# conference+DOI, three-author, manual, and the venue-tier variants that
# originally slipped through untranslated.
ENTRY_BOOK_SINGLE_AUTHOR = (
    "A. Novak, Lecture Notes on Fictional Devices, Imagina Publishing, 2018. Chapter 7."
)
ENTRY_JOURNAL = (
    "K. Alekhine, B. Montton, Threshold behaviour of invented reservoir models, "
    "Synth. J. Appl. Phys. 12 (2019) 341-358."
)
ENTRY_CONF_DOI = (
    "P. Valmary, et al., The invented transistor at forty, in: Proc. Fictitious Intl. "
    "Conference on Synth. Electron. (FICSE), 2021, https://doi.org/10.5555/FICSE.2021.0088."
)
ENTRY_THREE_AUTHORS = (
    "R. Tsubasa, J. Iyer, M. Kowalski, Screening lengths in reservoir-channel "
    "systems: a review, in: Synth. Rev. Lett., 2022, pp. 15-31."
)
ENTRY_MANUAL = (
    "T. Emeka, G. Lindqvist, Beta-ST Prefactor Manual, University of Imagina Press, 2024."
)

# Venue-tier variants (the shapes that originally slipped through untranslated).
ENTRY_SOLID_STATE = (
    "K. Alekhine, B. Montton, et al., Charge redistribution in narrow-gap fictional "
    "materials, Synth. Solid-State Electron. Rev. 12 (3) (2019) 341-358."
)
ENTRY_DEVICE_LETT = (
    "T. Emeka, X. Liang, et al., Beta-statistics prefactors for unmeasured "
    "channels, Fictional Electron Device Lett. 25 (2) (2024) 107-109."
)
ENTRY_PROC_NANOTECH = (
    "R. Tsubasa, J. Iyer, et al., Screening length reviews for reservoir-channel "
    "systems, Proc. Synth. Nanotech. Conference 3 (2022) 15-31."
)
ENTRY_SEMICOND = (
    "G. Lindqvist, M. Chan, et al., Threshold behaviour of invented reservoir "
    "devices with continuous solution from accumulation to inversion, "
    "Synth. Semicond. Sci. Technol. 24 (2021) 085005."
)


def test_bracket_label_still_skips() -> None:
    assert classify_skip("[12] A. Author, Some title, 2020.") == BIB


def test_single_author_book_skips() -> None:
    assert classify_skip(ENTRY_BOOK_SINGLE_AUTHOR) == BIB


def test_journal_entry_skips() -> None:
    assert classify_skip(ENTRY_JOURNAL) == BIB


def test_conf_doi_entry_skips() -> None:
    assert classify_skip(ENTRY_CONF_DOI) == BIB


def test_three_author_entry_skips() -> None:
    assert classify_skip(ENTRY_THREE_AUTHORS) == BIB


def test_manual_entry_skips() -> None:
    assert classify_skip(ENTRY_MANUAL) == BIB


def test_venue_tier_entries_skip() -> None:
    assert classify_skip(ENTRY_SOLID_STATE) == BIB
    assert classify_skip(ENTRY_DEVICE_LETT) == BIB
    assert classify_skip(ENTRY_PROC_NANOTECH) == BIB
    assert classify_skip(ENTRY_SEMICOND) == BIB


def test_body_prose_with_year_translates() -> None:
    assert (
        classify_skip(
            "As demonstrated in 2004, scaling continued for another decade before slowing down."
        )
        is None
    )


def test_body_mentioning_conference_translates() -> None:
    # Names + year + venue word, but not a citation shape (no title/pages/DOI).
    assert (
        classify_skip(
            "Hu and Ko presented their results at the conference in 1988 "
            "and the audience was convinced."
        )
        is None
    )


def test_short_citation_line_translates() -> None:
    assert classify_skip("Research anchors: [1], [2]") is None


def test_empty_is_none() -> None:
    assert classify_skip("") is None


ENTRY_IEEE_ACCESS = (
    "N. Paydavosi, S. Venugopalan, Y.S. Chauhan, J.P. Duarte, S. Jandhyala, "
    "A.M. Niknejad, C. Hu, BSIM-SPICE models enable FinFET and UTB IC designs, "
    "IEEE Access 1 (2013) 201."
)


def test_ieee_access_entry_skips() -> None:
    assert classify_skip(ENTRY_IEEE_ACCESS) == BIB


# The three chapter-3 entries that slipped through before the generic
# journal-volume / page-range-tail / publisher tiers (p24-26 references
# half-translated while sibling entries stayed English).
ENTRY_SINGLE_AUTHOR_PAGES = (
    "Y. Taur, An analytical solution to a double-gate MOSFET with undoped body, "
    "IEEE Electron Device Lett. 21 (5) (2000) 245 - 247."
)
ENTRY_GARBLED_VENUE_VOLUME = (
    "Y. Chen, J. Luo, A comparative study of double-gate and surrounding-gate "
    "MOSFETs in strong inversion and accumulation using an analytical model, "
    "Integrion 1 (2) (2001) 6."
)
ENTRY_PUBLISHER_ONLY = (
    "J. Roychowdhury, Numerical Simulation and Modelling of Electronic and "
    "Biochemical Systems, Now Publishers Inc., 2009."
)


def test_single_author_journal_with_page_range_skips() -> None:
    assert classify_skip(ENTRY_SINGLE_AUTHOR_PAGES) == BIB


def test_garbled_venue_with_volume_issue_skips() -> None:
    assert classify_skip(ENTRY_GARBLED_VENUE_VOLUME) == BIB


def test_publisher_only_book_entry_skips() -> None:
    assert classify_skip(ENTRY_PUBLISHER_ONLY) == BIB


def test_volume_like_prose_translates() -> None:
    # A year and a author-shaped token, but no entry shape: the volume cue
    # must require a venue-like capitalised word directly before the volume.
    assert (
        classify_skip(
            "In 2001, section 3 (2) of the standard was revised and Y. Taur "
            "reviewed the change for the working group."
        )
        is None
    )


def test_open_access_prose_translates() -> None:
    # Two initialled authors + year + the word 'access', but NOT an IEEE
    # Access / Journal venue — must not over-fire on prose.
    assert (
        classify_skip(
            "As A. Smith and B. Jones noted in their open access review of 2020, "
            "the results were widely reproduced by other groups."
        )
        is None
    )


def test_custom_bib_patterns_registration() -> None:
    from ubt.core.cleaners.skip_rules import register_bib_patterns, reset_custom_bib_patterns

    sample_entry = (
        "X. Wang, Y. Zhao, Neural processing architectures, Quantum Computing Review 2024."
    )
    # Before registration, "Quantum Computing Review" is not recognized as a venue
    assert classify_skip(sample_entry) is None

    try:
        register_bib_patterns(extra_venues=[r"Quantum Computing Review"])
        assert classify_skip(sample_entry) == BIB
    finally:
        reset_custom_bib_patterns()
        assert classify_skip(sample_entry) is None


def test_custom_bib_patterns_registration_is_thread_safe() -> None:
    """Concurrent registration must not lose patterns (review finding)."""
    import threading

    from ubt.core.cleaners.skip_rules import register_bib_patterns, reset_custom_bib_patterns

    sample_entry = (
        "X. Wang, Y. Zhao, Neural processing architectures, Quantum Computing Review 2024."
    )
    errors: list[BaseException] = []

    def _worker() -> None:
        try:
            register_bib_patterns(extra_venues=[r"Quantum Computing Review"])
        except BaseException as exc:  # surfaced by the assertion below
            errors.append(exc)

    threads = [threading.Thread(target=_worker) for _ in range(8)]
    for thread in threads:
        thread.start()
    for thread in threads:
        thread.join()

    assert not errors
    try:
        assert classify_skip(sample_entry) == BIB
    finally:
        reset_custom_bib_patterns()


# --- arXiv-era full-name references (author-initial count is zero) ----------
# The dominant modern citation style lists full author names, which score zero
# on ``_AUTHOR_RE`` and so never cleared the old ``authors >= N`` gates. Every
# one of these slipped to the LLM and came back with transliterated names
# (arXiv 2609.20519). Detection must key on the citation shape, not initials.
ENTRY_FULLNAME_NEURIPS = (
    "John Yang, Carlos Jimenez, Alexander Wettig, Kilian Lieret, Shunyu Yao, "
    "Karthik Narasimhan, and Ofir Press. Swe-agent: Agent-computer interfaces "
    "enable automated software engineering. Advances in Neural Information "
    "Processing Systems, 37: 50528-50652, 2024."
)
ENTRY_FULLNAME_ICLR = (
    "Jenny Zhang, Shengran Hu, Cong Lu, Robert Lange, and Jeff Clune. Darwin "
    "gödel machine: open-ended evolution of self-improving agents. In "
    "International Conference on Learning Representations, volume 2026, "
    "pages 104223-104294, 2026."
)
ENTRY_SINGLE_AUTHOR_URL = (
    "Wilson Lin. Towards self-driving codebases. Cursor research blog, 2026. "
    "URL https://cursor.com/blog/self-driving-codebases. Accessed 2026-08-17."
)
ENTRY_CORPORA_URL = (
    "Andrej Karpathy. autoresearch: The experiment loop. GitHub repository, "
    "2026. URL https://github.com/karpathy/autoresearch. Accessed 2026-08-17."
)
ENTRY_ETAL = (
    "Lakshya A Agrawal, Shangyin Tan, Dilara Soylu, Noah Ziems, et al. Gepa: "
    "Reflective prompt evolution can outperform reinforcement learning. 2025."
)


def test_full_name_reference_is_kept_verbatim() -> None:
    assert classify_skip(ENTRY_FULLNAME_NEURIPS) == BIB
    assert classify_skip(ENTRY_FULLNAME_ICLR) == BIB
    assert classify_skip(ENTRY_SINGLE_AUTHOR_URL) == BIB
    assert classify_skip(ENTRY_CORPORA_URL) == BIB
    assert classify_skip(ENTRY_ETAL) == BIB


def test_prose_list_item_without_citation_shape_is_still_translated() -> None:
    """The design-principle bullets in an intro are prose, not references:
    they carry no URL, year, venue, ``In <X>`` or page range and must not
    be swept up by the author-independent tiers."""
    assert (
        classify_skip(
            "Breadth and depth. Breadth expands hypothesis coverage, while depth "
            "repeatedly implements, reviews, and hardens promising candidates."
        )
        is None
    )
    assert (
        classify_skip(
            "Independent validation. Held-out evidence is evaluated only after a "
            "candidate is frozen and never returns to search."
        )
        is None
    )


# --- author byline: foreign names kept in romanization (GB/T 7714) ----------
BYLINE_MARKERS = (
    "Haozhe Liu 1* , Tian Ye 1 * , Sensen Gao 2† , Qihang Cao 2† , Yitong Li 1 † , Mingchen Zhuge"
)
BYLINE_PLAIN = "Duomin Wang 1 , Ruihua Zhang 1 , Ping Luo 1 , Lei Zhu 1 , Song Han 13"
BYLINE_SUPER = "Jane Doe ¹ ², John Smith ³, and Ada Lovelace"


def test_author_byline_is_kept_verbatim() -> None:
    for line in (BYLINE_MARKERS, BYLINE_PLAIN, BYLINE_SUPER):
        reason = classify_skip(line)
        assert reason is not None and "byline" in reason, line


def test_prose_and_reference_are_not_a_byline() -> None:
    # Narrative with lowercase words / verbs fails the all-names shape.
    assert (
        classify_skip(
            "As coding agents move from supervised code completion to unattended "
            "exploration, their work expands into long trajectories."
        )
        is None
    )
    # A single name is not a byline (needs >=2).
    assert classify_skip("Mingchen Zhuge") is None
    # A real reference (year + venue + page range) is caught as a bib entry,
    # never as a byline — the year disqualifies the byline shape.
    assert classify_skip(ENTRY_FULLNAME_NEURIPS) == BIB


def test_title_case_heading_lists_are_not_bylines() -> None:
    """A heading is structure the author wrote, not somebody's name list.

    Every segment being Capitalized was enough to call it a byline, which then
    shipped the heading untranslated with MTQE_PASSED — silently, in the one
    place a reader sees it first.
    """
    for line in (
        "Purpose, Scope, and Audience",
        "Introduction, Motivation, and Outline",
        "Risk, Return, and Reward",
        "War and Peace",
    ):
        assert classify_skip(line) is None, line
    # Structure the text alone cannot express: never byline-classify a heading.
    assert classify_skip("Deep Learning and Neural Networks", is_heading=True) is None
    # The real thing still matches.
    assert classify_skip(BYLINE_PLAIN) is not None


def test_cross_page_prose_starting_with_citation_is_not_skipped() -> None:
    """A cross-page paragraph continuation starting with '[3] yield...' must translate."""
    prose_continuation = (
        "[3] yield spatial composability at the granularity of a service. In practice, "
        "most software tolerates the lack of fine-grained composability by deferring to "
        "these coarse-grained mechanisms: a misbehaving module is handled by restarting "
        "the process, and a service dependency is managed by the container orchestrator."
    )
    assert classify_skip(prose_continuation) is None


def test_online_bibliography_without_year_is_skipped() -> None:
    """IEEE/ACM '[Online]. Available: https://...' references without a 4-digit year must skip."""
    ts_handbook = (
        "Microsoft, 'Declaration Merging.' [Online]. Available: "
        "https://www.typescriptlang.org/docs/handbook/declaration-merging.html"
    )
    py_howto = (
        "R. Hettinger, 'Descriptor HowTo Guide.' [Online]. Available: "
        "https://docs.python.org/3/howto/descriptor.html"
    )
    assert classify_skip(ts_handbook) == BIB
    assert classify_skip(py_howto) == BIB


def test_cs_book_and_proceedings_and_short_bib_entries_are_skipped() -> None:
    """Classic CS publishers (MIT Press, Addison-Wesley), CoRR abs volumes, and short citations must skip."""
    entries = (
        "B. C. Pierce, Types and Programming Languages . MIT Press, 2002.",
        "E. Gamma, R. Helm, R. Johnson, and J. Vlissides, Design Patterns: Elements of Reusable Object-Oriented Software . Boston, MA: Addison-Wesley, 1994.",
        "E. Burmako, 'Scala Macros: Let Our Powers Combine!,' in Proceedings of the 4th Workshop on Scala , in SCALA@ECOOP '13. 2013, p. 3:1-3:10. doi: 10.1145/2489837.2489840.",
        "C. Packer, V. Fang, S. G. Patil, K. Lin, S. Wooders, and J. E. Gonzalez, 'MemGPT: Towards LLMs as Operating Systems,' CoRR , vol. abs/2310.08560, 2023.",
        "M. Fowler, 'Event Sourcing.' 2005.",
        "C. Szyperski, Component Software: Beyond Object-Oriented Programming , 2nd ed. AddisonWesley, 2002.",
    )
    for entry in entries:
        assert classify_skip(entry) == BIB, f"Failed to skip bibliography entry: {entry!r}"


def test_in_bibliography_section_context_skips_all_entries() -> None:
    """Any citation-length non-heading block inside a References/Bibliography section must be skipped."""
    obscure_ref = "K. Satou and H. Tanaka, 'Unusual Self-Published Monograph Without Standard Venue,' Tokyo, 2024."
    assert classify_skip(obscure_ref, in_bibliography=True) == BIB
    assert classify_skip("References", is_heading=True, in_bibliography=True) is None


def test_technical_documentation_citations_are_skipped() -> None:
    """Technical documentation references with consultation/access dates (e.g. KV Cache Handbook p.33) must skip."""
    doc_entries = (
        "NVIDIA Transformer Engine documentation. PyTorch attention/inference parameters; K/V caching during decoding. Consulted September 2026.",
        "vLLM documentation. Automatic Prefix Caching, cache configuration, and prefix-cache isolation/security. Current documentation consulted September 2026.",
        "NVIDIA TensorRT-LLM documentation. KV Cache System, reuse, prioritized eviction, and host offloading. Current documentation consulted September 2026.",
        "vLLM documentation. KV Offloading Usage Guide and multi-tier offloading APIs. Current documentation consulted September 2026.",
        "vLLM documentation. Quantized KV Cache and CacheConfig storage dtype options. Current documentation consulted September 2026.",
    )
    for entry in doc_entries:
        assert classify_skip(entry) == BIB, f"Failed to skip documentation citation: {entry!r}"


def test_bibliography_section_survives_subheading_and_exits_on_appendix() -> None:
    """A sub-heading immediately below REFERENCES (e.g. 'Primary papers and current implementation sources')
    must NOT reset in_bibliography=False while bibliography entries follow, and must reset on a real post-bib section."""
    from ubt.core.engine.stages.ingest import update_bibliography_section_state
    from ubt.core.ir.models import BlockType, IRBlock

    blocks = [
        IRBlock(id="b330", spine_index=0, block_type=BlockType.HEADING, source_text="REFERENCES"),
        IRBlock(
            id="b331",
            spine_index=1,
            block_type=BlockType.HEADING,
            source_text="Primary papers and current implementation sources",
        ),
        IRBlock(
            id="b332",
            spine_index=2,
            block_type=BlockType.LIST_ITEM,
            source_text="A. Vaswani et al. Attention Is All You Need . NeurIPS 2017. arXiv:1706.03762.",
        ),
        IRBlock(
            id="b337",
            spine_index=3,
            block_type=BlockType.LIST_ITEM,
            source_text="Custom internal reference without standard venue or URL, 2026.",
        ),
        IRBlock(
            id="b343",
            spine_index=4,
            block_type=BlockType.HEADING,
            source_text="Appendix A: Proofs",
        ),
        IRBlock(
            id="b344",
            spine_index=5,
            block_type=BlockType.NARRATIVE,
            source_text="In this appendix we derive the lower bound on cache memory.",
        ),
    ]

    in_bib = False
    states: dict[str, bool] = {}
    for idx, b in enumerate(blocks):
        in_bib = update_bibliography_section_state(blocks, idx, in_bib)
        states[b.id] = in_bib

    assert states["b330"] is True
    assert states["b331"] is True
    assert states["b332"] is True
    assert states["b337"] is True
    assert states["b343"] is False
    assert states["b344"] is False

